name: Publish to PyPI
on:
  push:
    tags:
      - v*
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install build pytest expects
      - name: Build and install package in container 
        run: (python -m build --wheel && python -m pip install dist/*) 
      - name: Run tests
        run: python -m pytest
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
