name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies 
        run: python -m pip install build pytest expects
      - name: Build and install package in container
        run: (python -m build --wheel && python -m pip install dist/*)
      - name: Run tests
        run: python -m pytest
